SELECT LGCUSTOMER.Cust_Code, LGCUSTOMER.Cust_Fname, LGCUSTOMER.Cust_Lname, SUM(LGINVOICE.Inv_Total) AS 'Sum of Invoice Totals'
FROM LGCUSTOMER JOIN LGINVOICE ON LGCUSTOMER.Cust_Code = LGINVOICE.Cust_Code
WHERE LGINVOICE.Inv_Total > 1500
GROUP BY LGINVOICE.Cust_Code
ORDER BY SUM(LGINVOICE.Inv_Total) DESC;
