SELECT LGSUPPLIES.Vend_ID, LGVENDOR.Vend_Name, LGBRAND.Brand_Name, COUNT(*) AS 'Amount'
FROM LGVENDOR JOIN (LGSUPPLIES JOIN (LGPRODUCT JOIN LGBRAND ON LGPRODUCT.Brand_ID=LGBRAND.Brand_ID) ON LGSUPPLIES.Prod_SKU=LGPRODUCT.Prod_SKU) ON LGVENDOR.Vend_ID=LGSUPPLIES.Vend_ID
GROUP BY LGSUPPLIES.Vend_ID, LGPRODUCT.Brand_ID
ORDER BY LGVENDOR.Vend_Name, LGBRAND.Brand_Name;