SELECT CONCAT(M.Emp_Fname, ' ', M.Emp_Lname) AS 'Manager_Name', LGDEPARTMENT.Dept_Name, LGDEPARTMENT.Dept_Phone, CONCAT(E.Emp_Fname, ' ', E.Emp_Lname) AS 'Emp_Name', CONCAT(LGCUSTOMER.Cust_Fname, ' ', LGCUSTOMER.Cust_Lname) AS 'Cust_Name', LGINVOICE.Inv_Date, LGINVOICE.Inv_Total
FROM LGCUSTOMER JOIN (LGINVOICE JOIN (LGEMPLOYEE E JOIN (LGDEPARTMENT JOIN LGEMPLOYEE M ON LGDEPARTMENT.Emp_Num=M.Emp_Num) ON E.Dept_Num=LGDEPARTMENT.Dept_Num) ON LGINVOICE.Employee_ID=E.Emp_Num) ON LGCUSTOMER.Cust_Code=LGINVOICE.Cust_Code
WHERE Cust_Lname like 'Doe' AND Inv_Date='2013-03-23';
