SELECT LGCUSTOMER.Cust_Code, LGCUSTOMER.Cust_Fname, LGCUSTOMER.Cust_Lname, CONCAT(LGCUSTOMER.Cust_Street, ' ', LGCUSTOMER.Cust_City, ' ', LGCUSTOMER.Cust_Province, ' ', LGCUSTOMER.Cust_ZIP) AS 'Full_Address', LGINVOICE.Inv_Date, LGINVOICE.Inv_Total
FROM LGCUSTOMER JOIN LGINVOICE ON LGCUSTOMER.Cust_Code=LGINVOICE.Cust_Code
WHERE LGCUSTOMER.Cust_Province like 'Gauteng'
GROUP BY LGCUSTOMER.Cust_Code
HAVING MAX(Inv_Total);
