SELECT LGDEPARTMENT.Dept_Num, LGDEPARTMENT.Dept_Name, LGDEPARTMENT.Dept_Phone, LGDEPARTMENT.Emp_Num, LGEMPLOYEE.Emp_Lname
FROM LGDEPARTMENT JOIN LGEMPLOYEE ON LGDEPARTMENT.Emp_Num = LGEMPLOYEE.Emp_Num
WHERE LGEMPLOYEE.Emp_Title like "manager"
ORDER BY LGDEPARTMENT.Dept_Name;
