SELECT LGSALARY_HISTORY.Sal_Amount
FROM LGSALARY_HISTORY JOIN LGEMPLOYEE ON LGSALARY_HISTORY.Emp_Num=LGEMPLOYEE.Emp_Num
WHERE LGEMPLOYEE.Dept_Num=300 AND LGSALARY_HISTORY.Sal_End IS NULL
ORDER BY LGSALARY_HISTORY.Sal_Amount DESC;
