SELECT LGBRAND.Brand_Name, LGBRAND.Brand_Type, AVG(LGPRODUCT.Prod_Price) AS 'Average', SUM(LGLINE.Line_Qty) AS 'Total Units Sold'
FROM LGBRAND JOIN (LGPRODUCT JOIN LGLINE ON LGPRODUCT.Prod_SKU=LGLINE.Prod_SKU) ON LGBRAND.Brand_ID=LGPRODUCT.Brand_ID
GROUP BY LGBRAND.Brand_ID;
