SELECT LGEMPLOYEE.Emp_Num, LGEMPLOYEE.Emp_Lname, LGEMPLOYEE.Emp_Fname, LGSALARY_HISTORY.Sal_From, LGSALARY_HISTORY.Sal_End, LGSALARY_HISTORY.Sal_Amount
FROM LGEMPLOYEE INNER JOIN LGSALARY_HISTORY ON LGEMPLOYEE.Emp_Num=LGSALARY_HISTORY.Emp_Num
WHERE LGEMPLOYEE.Emp_Num = 83731 OR LGEMPLOYEE.Emp_Num = 83745 OR LGEMPLOYEE.Emp_Num = 84039
ORDER BY LGEMPLOYEE.Emp_Num, LGSALARY_HISTORY.Sal_From;
