SELECT DISTINCT LGCUSTOMER.Cust_Fname, LGCUSTOMER.Cust_Lname, LGCUSTOMER.Cust_Street, LGCUSTOMER.Cust_City, LGCUSTOMER.Cust_Province, LGCUSTOMER.Cust_Zip
FROM LGCUSTOMER JOIN (LGINVOICE JOIN (LGLINE JOIN (LGPRODUCT JOIN LGBRAND ON LGPRODUCT.Brand_ID=LGBRAND.Brand_ID) ON LGLINE.Prod_SKU=LGPRODUCT.Prod_SKU) ON LGINVOICE.Inv_Num=LGLINE.Inv_Num) ON LGCUSTOMER.Cust_Code=LGINVOICE.Cust_Code
WHERE LGBRAND.Brand_Name like 'Coruscant Painters' AND LGPRODUCT.Prod_Category like 'Top Coat' AND (LGINVOICE.Inv_Date BETWEEN '2011-07-15' AND '2013-07-31')
ORDER BY LGCUSTOMER.Cust_Province, LGCUSTOMER.Cust_Lname, LGCUSTOMER.Cust_Fname;
