SELECT LGINVOICE.Inv_Num, LGLINE.Prod_SKU, LGPRODUCT.Prod_Desc, LGBRAND.Brand_ID
FROM LGINVOICE JOIN (LGLINE JOIN (LGPRODUCT JOIN LGBRAND ON LGPRODUCT.Brand_ID=LGBRAND.Brand_ID) ON LGLINE.Prod_SKU=LGPRODUCT.Prod_SKU) ON LGINVOICE.Inv_Num=LGLINE.Inv_Num
WHERE LGPRODUCT.Prod_Category like 'sealer' OR LGPRODUCT.Prod_Category like 'top coat'
GROUP BY LGPRODUCT.Brand_ID, LGINVOICE.Inv_Num;