SELECT LGEMPLOYEE.Emp_Num, LGEMPLOYEE.Emp_Fname, LGEMPLOYEE.Emp_Lname, MAX(LGSALARY_HISTORY.Sal_Amount) AS 'Largest Salary Amount'
FROM LGEMPLOYEE JOIN LGSALARY_HISTORY ON LGEMPLOYEE.Emp_Num=LGSALARY_HISTORY.Emp_Num
WHERE LGEMPLOYEE.Dept_Num = 200
GROUP BY LGEMPLOYEE.Emp_Num
ORDER BY MAX(LGSALARY_HISTORY.Sal_Amount) DESC;
