SELECT LGEMPLOYEE.Emp_Num, LGEMPLOYEE.Emp_Fname, LGEMPLOYEE.Emp_Lname, LGSALARY_HISTORY.Sal_Amount
FROM LGEMPLOYEE JOIN LGSALARY_HISTORY ON LGEMPLOYEE.Emp_Num=LGSALARY_HISTORY.Emp_Num
WHERE LGEMPLOYEE.Dept_Num = 200
<<<<<<< HEAD
ORDER BY LGSALARY_HISTORY.Sal_Amount
LIMIT 1;
=======
GROUP BY LGEMPLOYEE.Emp_Num
ORDER BY LGSALARY_HISTORY.Sal_Amount;
>>>>>>> Fixed Q16
