SELECT L1.Cust_Code, LGCUSTOMER.Cust_Fname, LGCUSTOMER.Cust_Lname
FROM LGINVOICE L1 JOIN (LGCUSTOMER JOIN LGINVOICE L2 ON LGCUSTOMER.Cust_Code=L2.Cust_Code) ON L1.Cust_Code=LGCUSTOMER.Cust_Code
WHERE L1.Employee_ID=83649 AND L2.Employee_ID=83677
ORDER BY LGCUSTOMER.Cust_Lname, LGCUSTOMER.Cust_Fname;
